application: lectroid-sactraffic
version: 2
runtime: python
api_version: 1

default_expiration: "365d"

handlers:
- url: /atom
  script: handlers/atom.py

- url: /json
  script: handlers/json.py

- url: /update
  script: handlers/update.py
  login: admin

- url: /purge
  script: handlers/purge.py
  login: admin

# Redirections
- url: /rss.php
  script: handlers/redirect.py

# Static stuff
- url: /stylesheets
  static_dir: static/stylesheets
  expiration: "10m"

- url: /javascript
  static_dir: static/javascript
  expiration: "10m"

- url: /apple-touch-icon.png
  static_files: static/images/sactraffic.png
  upload: static/images/sactraffic.png

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /
  static_files: static/index.html
  upload: static/index.html
  expiration: "10m"

- url: /(.*)
  static_files: static/\1
  upload: static/(.*)

builtins:
- deferred: on

inbound_services:
- warmup
