application: lectroid-sactraffic
version: 1
runtime: python
api_version: 1

default_expiration: "365d"

handlers:

# Dynamic handlers

- url: /json
  script: handlers/json.py

- url: /atom
  script: handlers/atom.py

- url: /getcameras
  script: handlers/getcameras.py

- url: /incident
  script: handlers/incident.py

- url: /showcamera
  script: handlers/showcamera.py

- url: /sitemap
  script: handlers/sitemap.py

- url: /incident.php
  script: handlers/redirect.py

- url: /incident.html
  script: handlers/redirect.py

- url: /rss.php
  script: handlers/redirect.py

- url: /json/STCC-STCC.json
  script: handlers/redirect.py

- url: /update-helper
  script: handlers/update-helper.py

- url: /update
  script: handlers/update.py
  login: admin

- url: /purge
  script: handlers/purge.py
  login: admin

- url: /_ah/queue/deferred
  script: $PYTHON_LIB/google/appengine/ext/deferred/handler.py
  login: admin

# Static handlers

- url: /images
  static_dir: static/images

- url: /stylesheets
  static_dir: static/stylesheets
  expiration: "10m"

- url: /javascript
  static_dir: static/javascript
  expiration: "10m"

- url: /apple-touch-icon.png
  static_files: static/images/sactraffic.png
  upload: static/images/sactraffic.png

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /(.*\.html)
  static_files: static/\1
  upload: static/(.*\.html)
  expiration: "10m"

- url: /
  static_files: static/index.html
  upload: static/index.html


builtins:
- remote_api: on
