application: lectroid-sactraffic-hrd
version: 3
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "365d"

handlers:
- url: /atom
  script: handlers.atom_data.application

- url: /json
  script: handlers.json_data.application

- url: /update
  script: handlers.update.application
  login: admin

- url: /purge
  script: handlers.purge.application
  login: admin

# Static stuff
- url: /sactraffic.min.js
  static_files: static/sactraffic.min.js
  upload: static/sactraffic.min.js
  expiration: "10m"

- url: /sactraffic.min.css
  static_files: static/sactraffic.min.css
  upload: static/sactraffic.min.css
  expiration: "10m"

- url: /apple-touch-icon.png
  static_files: static/images/sactraffic.png
  upload: static/images/sactraffic.png

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /
  static_files: static/index.html
  upload: static/index.html
  expiration: "10m"

- url: /(.*)
  static_files: static/\1
  upload: static/(.*)

builtins:
- deferred: on

skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^static/src/.*
